package com.hebeu.miniprogram.status;

public class ServiceStatus {

    public final static String USER_NOT_EXIST = "USER_NOT_EXIST";
    public final static String USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
    public final static String USER_CHECK_FAILED = "USER_CHECK_FAILED";
    public final static String UPDATE_PHONE_SUCCESS = "UPDATE_PHONE_SUCCESS";
    public final static String UPDATE_PHONE_FAILED = "UPDATE_PHONE_FAILED";
    public final static String RESUME_POSTED = "RESUME_POSTED";
    public final static String RESUME_REJECTED = "RESUME_REJECTED";
    public final static String RESUME_ACCEPTED = "RESUME_ACCEPTED";
    public final static String USER_DELETED_SUCCESS = "USER_DELETED_SUCCESS";
    public final static String USER_DELETED_FAILED = "USER_DELETED_FAILED";
    public final static String USER_INSERT_SUCCESS = "USER_INSERT_SUCCESS";
    public final static String USER_INSERT_FAILED = "USER_INSERT_FAILED";
    public final static String INSERT_RECRUIT_INFO_SUCCESS = "INSERT_RECRUIT_INFO_SUCCESS";
    public final static String INSERT_RECRUIT_INFO_FAILED = "INSERT_RECRUIT_INFO_FAILED";
    public final static String SEARCH_RECRUIT_BY_USER_ID_FAILED = "SEARCH_RECRUIT_BY_USER_ID_FAILED";
    public final static String SEARCH_RECRUIT_BY_RELEASE_TIME_FAILED = "SEARCH_RECRUIT_BY_RELEASE_TIME_FAILED";
    public final static String SEARCH_RECRUIT_BY_WORK_TYPE_FAILED = "SEARCH_RECRUIT_BY_WORK_TYPE_FAILED";
    public final static String SEARCH_RECRUIT_BY_WORK_PERIOD_FAILED = "SEARCH_RECRUIT_BY_WORK_PERIOD_FAILED";
    public final static String SEARCH_RECRUIT_BY_WORK_PAYMENT_FAILED = "SEARCH_RECRUIT_BY_WORK_PAYMENT_FAILED";
    public final static String SEARCH_RECRUIT_BY_WORK_LOCATION_FAILED = "SEARCH_RECRUIT_BY_WORK_LOCATION_FAILED";
    public final static String SEARCH_RECRUIT_BY_RECRUIT_TYPE_FAILED = "SEARCH_RECRUIT_BY_RECRUIT_TYPE_FAILED";
    public final static String SEARCH_RECRUIT_BY_RECRUIT_POSITION_FAILED = "SEARCH_RECRUIT_BY_RECRUIT_POSITION_FAILED";
    public final static String SEARCH_RECRUIT_BY_RECRUIT_ID_FAILED = "SEARCH_RECRUIT_BY_RECRUIT_ID_FAILED";
    public final static String SEARCH_ALL_RECRUIT_FAILED = "SEARCH_ALL_RECRUIT_FAILED";
    public final static String DELETE_RECRUIT_INFO_FAILED = "DELETE_RECRUIT_INFO_FAILED";
    public final static String DELETE_RECRUIT_INFO_SUCCESS = "DELETE_RECRUIT_INFO_SUCCESS";
    public final static String UPDATE_RECRUIT_INFO_FAILED = "UPDATE_RECRUIT_INFO_FAILED";
    public final static String UPDATE_RECRUIT_INFO_SUCCESS = "UPDATE_RECRUIT_INFO_SUCCESS";
    public final static String SEARCH_RECRUIT_BY_ENTERPRISE_NAME_FAILED = "SEARCH_RECRUIT_BY_ENTERPRISE_NAME_FAILED";
    public final static String INSERT_EXPECTED_JOB_INFO_SUCCESS = "INSERT_EXPECTED_JOB_INFO_SUCCESS";
    public final static String INSERT_EXPECTED_JOB_INFO_FAILED = "INSERT_EXPECTED_JOB_INFO_FAILED";
    public final static String DELETE_EXPECTED_JOB_INFO_SUCCESS = "DELETE_EXPECTED_JOB_INFO_SUCCESS";
    public final static String DELETE_EXPECTED_JOB_INFO_FAILED = "DELETE_EXPECTED_JOB_INFO_FAILED";
    public final static String SEARCH_ALL_EXPECTED_JOB_INFO_FAILED = "SEARCH_ALL_EXPECTED_JOB_INFO_FAILED";
    public final static String SEARCH_EXPECTED_JOB_INFO_BY_USER_ID = "SEARCH_EXPECTED_JOB_INFO_BY_USER_ID";
    public final static String UPDATE_EXPECTED_JOB_INFO_FAILED = "UPDATE_EXPECTED_JOB_INFO_FAILED";
    public final static String UPDATE_EXPECTED_JOB_INFO_SUCCESS = "UPDATE_EXPECTED_JOB_INFO_SUCCESS";
    public final static String DELETE_RESUME_INFO_SUCCESS = "DELETE_RESUME_INFO_SUCCESS";
    public final static String DELETE_RESUME_INFO_FAILED = "DELETE_RESUME_INFO_FAILED";
    public final static String SEARCH_ALL_RESUME_INFO_FAILED = "SEARCH_ALL_RESUME_INFO_FAILED";
    public final static String SEARCH_RESUME_INFO_BY_USER_ID_FAILED = "SEARCH_RESUME_INFO_BY_USER_ID_FAILED";
    public final static String SEARCH_RESUME_INFO_BY_RESUME_ID_FAILED = "SEARCH_RESUME_INFO_BY_RESUME_ID_FAILED";
    public final static String SEARCH_RESUME_INFO_BY_RECRUIT_ID_FAILED = "SEARCH_RESUME_INFO_BY_RECRUIT_ID_FAILED";
    public final static String UPDATE_RESUME_INFO_STATUS_SUCCESS = "UPDATE_RESUME_INFO_STATUS_SUCCESS";
    public final static String UPDATE_RESUME_INFO_STATUS_FAILED = "UPDATE_RESUME_INFO_STATUS_FAILED";
    public final static String UPDATE_RESUME_INFO_SUCCESS = "UPDATE_RESUME_INFO_SUCCESS";
    public final static String UPDATE_RESUME_INFO_FAILED = "UPDATE_RESUME_INFO_FAILED";


}
